# Generated by Django 4.2.1 on 2023-06-22 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venta_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 3, 52, 19, 318487, tzinfo=datetime.timezone.utc)),
        ),
    ]
