# Generated by Django 4.2.1 on 2023-06-22 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 4, 13, 36, 224686, tzinfo=datetime.timezone.utc)),
        ),
    ]
