# Generated by Django 4.2.1 on 2023-06-23 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 21, 2, 13, 149477, tzinfo=datetime.timezone.utc)),
        ),
    ]
