# Generated by Django 4.2.1 on 2023-06-24 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 0, 27, 27, 85337, tzinfo=datetime.timezone.utc)),
        ),
    ]
