# Generated by Django 4.2.7 on 2023-11-28 06:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2023, 11, 28, 6, 4, 50, 336704, tzinfo=datetime.timezone.utc))),
                ('total', models.IntegerField()),
                ('estado', models.CharField(default='EN PREPARACION', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Ropa',
        ),
        migrations.RenameModel(
            old_name='Detalle',
            new_name='Historial',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.AlterField(
            model_name='historial',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
