# Generated by Django 4.2.7 on 2023-11-30 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_estado_rename_producto_ropa_rename_detalle_historial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='venta',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='producto',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ropa',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ropa',
            old_name='precio',
            new_name='rut',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='total',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='stock',
        ),
        migrations.AddField(
            model_name='ropa',
            name='email',
            field=models.EmailField(default=30112023, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='id',
            field=models.AutoField(default=30112023, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='talla',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('x', 'X'), ('xl', 'XL'), ('xxl', 'XXL')], default='s', max_length=3),
        ),
        migrations.AddField(
            model_name='ropa',
            name='tipo',
            field=models.CharField(choices=[('nueva', 'NUEVA'), ('usada', 'USADA')], default='nueva', max_length=5),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 11, 30, 17, 42, 0, 802548, tzinfo=datetime.timezone.utc)),
        ),
    ]
